DEBUG = True
USERNAME = 'root'
PASSWORD = 'root'
SERVER = 'localhost'
DB = 'cpems_db'

SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'
SQLALCHEMY_TRACK_MODIFICATIONS = True
SECRET_KEY = "5516500a750bfc88c0832fab"
BABEL_DEFAULT_LOCALE = 'pt'
