"""empty message

Revision ID: 09dcae131059
Revises: 02da9e34c3e9
Create Date: 2023-12-10 13:24:07.021016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09dcae131059'
down_revision = '02da9e34c3e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_requests', schema=None) as batch_op:
        batch_op.alter_column('protocolo_pat',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_tarefa',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_requests', schema=None) as batch_op:
        batch_op.alter_column('id_tarefa',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('protocolo_pat',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
