"""empty message

Revision ID: 22ab2757143c
Revises: 00c98d51f66b
Create Date: 2023-11-07 19:22:02.493177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22ab2757143c'
down_revision = '00c98d51f66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_usuarios', schema=None) as batch_op:
        batch_op.alter_column('usuario',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('tipo_acesso',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_usuarios', schema=None) as batch_op:
        batch_op.alter_column('tipo_acesso',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.alter_column('usuario',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
