"""empty message

Revision ID: 3934fca85fb3
Revises: ee9affbb906e
Create Date: 2023-12-02 14:10:17.921061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3934fca85fb3'
down_revision = 'ee9affbb906e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_designados', schema=None) as batch_op:
        batch_op.alter_column('id_servidor',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_designados', schema=None) as batch_op:
        batch_op.alter_column('id_servidor',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
