"""empty message

Revision ID: 3af9fbf23d5f
Revises: 99769fe2cba0
Create Date: 2023-12-16 18:21:36.325163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3af9fbf23d5f'
down_revision = '99769fe2cba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_processos', schema=None) as batch_op:
        batch_op.drop_column('tipo_determinacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_processos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_determinacao', mysql.VARCHAR(length=60), nullable=False))

    # ### end Alembic commands ###
