"""empty message

Revision ID: 40ef0ff982e8
Revises: 514da90cf942
Create Date: 2023-12-09 20:46:06.104708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40ef0ff982e8'
down_revision = '514da90cf942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processo_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('protocolo_pat', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('resposta', sa.String(length=2048), nullable=True))
        batch_op.drop_constraint('tb_requests_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_processos', ['processo_id'], ['id'])
        batch_op.drop_column('id_designado')
        batch_op.drop_column('competencia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competencia', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('id_designado', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_requests_ibfk_1', 'tb_designados', ['id_designado'], ['id'])
        batch_op.drop_column('resposta')
        batch_op.drop_column('protocolo_pat')
        batch_op.drop_column('processo_id')

    # ### end Alembic commands ###
