"""empty message

Revision ID: 47ec8e0f5c5a
Revises: ed43efee8a62
Create Date: 2024-02-18 18:52:52.125553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47ec8e0f5c5a'
down_revision = 'ed43efee8a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_competencias', schema=None) as batch_op:
        batch_op.drop_column('total_atribuicoes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_competencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_atribuicoes', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
