"""empty message

Revision ID: 514da90cf942
Revises: 3cc7fd903c3e
Create Date: 2023-12-09 20:22:13.912212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '514da90cf942'
down_revision = '3cc7fd903c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_designado', sa.Integer(), nullable=True),
    sa.Column('competencia', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_designado'], ['tb_designados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_designados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('siape_id_servidor', sa.Integer(), nullable=True))
        batch_op.alter_column('siape_servidor',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('tb_designados_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_id_servidores', ['siape_id_servidor'], ['siape_servidor'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_designados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_designados_ibfk_1', 'tb_id_servidores', ['siape_servidor'], ['siape_servidor'])
        batch_op.alter_column('siape_servidor',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('siape_id_servidor')

    op.drop_table('tb_requests')
    # ### end Alembic commands ###
