"""empty message

Revision ID: 52fb32aba93b
Revises: 544d0b445cb2
Create Date: 2023-12-23 23:09:08.253212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52fb32aba93b'
down_revision = '544d0b445cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_requests', schema=None) as batch_op:
        batch_op.alter_column('responsaveis_siape',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_requests', schema=None) as batch_op:
        batch_op.alter_column('responsaveis_siape',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
