"""empty message

Revision ID: 68cd40f494f2
Revises: 52fb32aba93b
Create Date: 2024-01-26 17:20:35.532715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68cd40f494f2'
down_revision = '52fb32aba93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ação', sa.String(length=100), nullable=True))
        batch_op.alter_column('responsaveis_siape',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_requests', schema=None) as batch_op:
        batch_op.alter_column('responsaveis_siape',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('ação')

    # ### end Alembic commands ###
