"""empty message

Revision ID: 69c61e4c8319
Revises: 40ef0ff982e8
Create Date: 2023-12-09 21:35:14.588455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69c61e4c8319'
down_revision = '40ef0ff982e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_requisicao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('info', sa.String(length=10000), nullable=True))
        batch_op.alter_column('resposta',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_requests', schema=None) as batch_op:
        batch_op.alter_column('resposta',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=2048),
               existing_nullable=True)
        batch_op.drop_column('info')
        batch_op.drop_column('data_requisicao')

    # ### end Alembic commands ###
