"""empty message

Revision ID: 6fb9afcb7e6e
Revises: ac7ffbf2cc9a
Create Date: 2023-12-02 19:17:56.371407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fb9afcb7e6e'
down_revision = 'ac7ffbf2cc9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_designados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_servidor', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tb_id_servidores', ['id_servidor'], ['id'])

    with op.batch_alter_table('tb_id_servidores', schema=None) as batch_op:
        batch_op.alter_column('siape_servidor',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['siape_servidor'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_id_servidores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('siape_servidor',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tb_designados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_servidor')

    # ### end Alembic commands ###
