"""empty message

Revision ID: 72119ca55411
Revises: 2b493b3941ed
Create Date: 2023-12-02 15:00:40.740018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72119ca55411'
down_revision = '2b493b3941ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_designados', schema=None) as batch_op:
        batch_op.drop_index('id_servidor')

    with op.batch_alter_table('tb_id_servidores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('siape_servidor', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_id_servidores', schema=None) as batch_op:
        batch_op.drop_column('siape_servidor')

    with op.batch_alter_table('tb_designados', schema=None) as batch_op:
        batch_op.create_index('id_servidor', ['id_servidor'], unique=False)

    # ### end Alembic commands ###
