"""empty message

Revision ID: 73ccb0846295
Revises: 72119ca55411
Create Date: 2023-12-02 15:56:42.753820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ccb0846295'
down_revision = '72119ca55411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_designados', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id_servidor'])
        batch_op.create_foreign_key(None, 'tb_id_servidores', ['id_servidor'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_designados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
