"""empty message

Revision ID: 92b735573589
Revises: 47ec8e0f5c5a
Create Date: 2024-02-18 20:56:31.107283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b735573589'
down_revision = '47ec8e0f5c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_atribuicoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_designado', sa.Integer(), nullable=True),
    sa.Column('nome_servico', sa.String(length=250), nullable=True),
    sa.Column('dt_atribuicao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_designado'], ['tb_designados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_atribuicoes')
    # ### end Alembic commands ###
