"""empty message

Revision ID: 99769fe2cba0
Revises: 09dcae131059
Create Date: 2023-12-16 16:13:16.525762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99769fe2cba0'
down_revision = '09dcae131059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_processos', schema=None) as batch_op:
        batch_op.alter_column('fase_demanda',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_processos', schema=None) as batch_op:
        batch_op.alter_column('fase_demanda',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
