"""empty message

Revision ID: a84ef9ca02d3
Revises: 
Create Date: 2023-11-07 18:59:55.516938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84ef9ca02d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_designados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_servidor', sa.String(length=80), nullable=True),
    sa.Column('siape_servidor', sa.Integer(), nullable=True),
    sa.Column('id_servidor', sa.Integer(), nullable=True),
    sa.Column('contato_servidor', sa.String(length=20), nullable=True),
    sa.Column('email_servidor', sa.String(length=50), nullable=False),
    sa.Column('unidade_servidor', sa.String(length=20), nullable=True),
    sa.Column('gex_servidor', sa.String(length=20), nullable=True),
    sa.Column('email_sard_servidor', sa.String(length=50), nullable=False),
    sa.Column('email_gex_servidor', sa.String(length=50), nullable=False),
    sa.Column('afastamento_servidor', sa.Boolean(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_gex_servidor'),
    sa.UniqueConstraint('email_sard_servidor'),
    sa.UniqueConstraint('email_servidor')
    )
    op.create_table('tb_usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.String(length=30), nullable=False),
    sa.Column('siape', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('nr_telefone', sa.String(length=30), nullable=False),
    sa.Column('senha', sa.String(length=60), nullable=False),
    sa.Column('tipo_acesso', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tb_ferias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designado_id', sa.Integer(), nullable=False),
    sa.Column('periodo_1_inicio', sa.Date(), nullable=True),
    sa.Column('periodo_1_fim', sa.Date(), nullable=True),
    sa.Column('periodo_2_inicio', sa.Date(), nullable=True),
    sa.Column('periodo_2_fim', sa.Date(), nullable=True),
    sa.Column('periodo_3_inicio', sa.Date(), nullable=True),
    sa.Column('periodo_3_fim', sa.Date(), nullable=True),
    sa.Column('periodo_4_inicio', sa.Date(), nullable=True),
    sa.Column('periodo_4_fim', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['designado_id'], ['tb_designados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_processos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nr_processo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('tipo_determinacao', sa.String(length=20), nullable=True),
    sa.Column('protocolo_pat', sa.Integer(), nullable=True),
    sa.Column('status_pat', sa.String(length=20), nullable=True),
    sa.Column('nome_responsavel_pat', sa.String(length=80), nullable=True),
    sa.Column('nome_servico_pat', sa.String(length=100), nullable=True),
    sa.Column('autoridade_coatora', sa.String(length=50), nullable=True),
    sa.Column('vara_origem', sa.String(length=50), nullable=True),
    sa.Column('fase_demanda', sa.String(length=50), nullable=True),
    sa.Column('status_demanda', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.String(length=1024), nullable=True),
    sa.Column('prazo_dias', sa.Integer(), nullable=True),
    sa.Column('data_prazo', sa.DateTime(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('data_atribuicao', sa.DateTime(), nullable=True),
    sa.Column('data_cumprimento', sa.DateTime(), nullable=True),
    sa.Column('responsavel_demanda', sa.Integer(), nullable=True),
    sa.Column('criador_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_conclusao_demanda', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criador_id'], ['tb_usuarios.id'], ),
    sa.ForeignKeyConstraint(['responsavel_conclusao_demanda'], ['tb_usuarios.id'], ),
    sa.ForeignKeyConstraint(['responsavel_demanda'], ['tb_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nr_processo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_processos')
    op.drop_table('tb_ferias')
    op.drop_table('tb_usuarios')
    op.drop_table('tb_designados')
    # ### end Alembic commands ###
