"""empty message

Revision ID: ab93e5831c4b
Revises: 375a29643d12
Create Date: 2023-11-25 14:35:51.325345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab93e5831c4b'
down_revision = '375a29643d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_despacho',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=False),
    sa.Column('data_despacho', sa.DateTime(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['tb_processos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_processos', schema=None) as batch_op:
        batch_op.alter_column('tipo_determinacao',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('prioridade_demanda',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_processos', schema=None) as batch_op:
        batch_op.alter_column('prioridade_demanda',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('tipo_determinacao',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)

    op.drop_table('tb_despacho')
    # ### end Alembic commands ###
