"""empty message

Revision ID: ac7ffbf2cc9a
Revises: 73ccb0846295
Create Date: 2023-12-02 18:44:50.468953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7ffbf2cc9a'
down_revision = '73ccb0846295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_designados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_servidor', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['id_servidor'])
        batch_op.create_foreign_key(None, 'tb_id_servidores', ['id_servidor'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_designados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('id_servidor')

    # ### end Alembic commands ###
