"""empty message

Revision ID: ad3dd8db24b9
Revises: 69c61e4c8319
Create Date: 2023-12-09 21:50:26.344713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad3dd8db24b9'
down_revision = '69c61e4c8319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_requests', schema=None) as batch_op:
        batch_op.alter_column('resposta',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_requests', schema=None) as batch_op:
        batch_op.alter_column('resposta',
               existing_type=sa.String(length=100),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)

    # ### end Alembic commands ###
