"""empty message

Revision ID: b5f80389540e
Revises: ab93e5831c4b
Create Date: 2023-11-25 15:31:13.829969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f80389540e'
down_revision = 'ab93e5831c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_despacho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsavel_despacho', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tb_usuarios', ['responsavel_despacho'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_despacho', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('responsavel_despacho')

    # ### end Alembic commands ###
