"""empty message

Revision ID: bf7692eefdfa
Revises: b5f80389540e
Create Date: 2023-11-27 19:43:10.738701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7692eefdfa'
down_revision = 'b5f80389540e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_processos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_unidade_pat', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_processos', schema=None) as batch_op:
        batch_op.drop_column('nome_unidade_pat')

    # ### end Alembic commands ###
