"""empty message

Revision ID: d6bac09a5fb5
Revises: 6fb9afcb7e6e
Create Date: 2023-12-02 19:34:42.318016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6bac09a5fb5'
down_revision = '6fb9afcb7e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_designados', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tb_id_servidores', ['siape_servidor'], ['siape_servidor'])
        batch_op.drop_column('id_servidor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_designados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_servidor', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
