"""empty message

Revision ID: ee9affbb906e
Revises: 7445e85c2ed5
Create Date: 2023-12-02 14:09:38.122812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9affbb906e'
down_revision = '7445e85c2ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_designados', schema=None) as batch_op:
        batch_op.drop_index('email_gex_servidor')
        batch_op.drop_index('email_sard_servidor')
        batch_op.drop_index('email_servidor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_designados', schema=None) as batch_op:
        batch_op.create_index('email_servidor', ['email_servidor'], unique=False)
        batch_op.create_index('email_sard_servidor', ['email_sard_servidor'], unique=False)
        batch_op.create_index('email_gex_servidor', ['email_gex_servidor'], unique=False)

    # ### end Alembic commands ###
